#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-origin
Version  : 2.2.2
Release  : 6
URL      : https://rubygems.org/downloads/origin-2.2.2.gem
Source0  : https://rubygems.org/downloads/origin-2.2.2.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-rdoc

%description
Origin
-------
This is the legacy repository of the Origin gem, which has been merged into the official Mongoid codebase
after version 2.2.0.
You can find the code in the MongoDB Mongoid repository [here](https://github.com/mongodb/mongoid).

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n origin-2.2.2
gem spec %{SOURCE0} -l --ruby > rubygem-origin.gemspec

%build
export LANG=C
gem build rubygem-origin.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
origin-2.2.2.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/origin-2.2.2.gem
/usr/lib64/ruby/gems/2.3.0/gems/origin-2.2.2/CHANGELOG.md
/usr/lib64/ruby/gems/2.3.0/gems/origin-2.2.2/LICENSE
/usr/lib64/ruby/gems/2.3.0/gems/origin-2.2.2/README.md
/usr/lib64/ruby/gems/2.3.0/gems/origin-2.2.2/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/origin-2.2.2/lib/origin.rb
/usr/lib64/ruby/gems/2.3.0/gems/origin-2.2.2/lib/origin/aggregable.rb
/usr/lib64/ruby/gems/2.3.0/gems/origin-2.2.2/lib/origin/extensions.rb
/usr/lib64/ruby/gems/2.3.0/gems/origin-2.2.2/lib/origin/extensions/array.rb
/usr/lib64/ruby/gems/2.3.0/gems/origin-2.2.2/lib/origin/extensions/big_decimal.rb
/usr/lib64/ruby/gems/2.3.0/gems/origin-2.2.2/lib/origin/extensions/boolean.rb
/usr/lib64/ruby/gems/2.3.0/gems/origin-2.2.2/lib/origin/extensions/date.rb
/usr/lib64/ruby/gems/2.3.0/gems/origin-2.2.2/lib/origin/extensions/date_time.rb
/usr/lib64/ruby/gems/2.3.0/gems/origin-2.2.2/lib/origin/extensions/hash.rb
/usr/lib64/ruby/gems/2.3.0/gems/origin-2.2.2/lib/origin/extensions/nil_class.rb
/usr/lib64/ruby/gems/2.3.0/gems/origin-2.2.2/lib/origin/extensions/numeric.rb
/usr/lib64/ruby/gems/2.3.0/gems/origin-2.2.2/lib/origin/extensions/object.rb
/usr/lib64/ruby/gems/2.3.0/gems/origin-2.2.2/lib/origin/extensions/range.rb
/usr/lib64/ruby/gems/2.3.0/gems/origin-2.2.2/lib/origin/extensions/regexp.rb
/usr/lib64/ruby/gems/2.3.0/gems/origin-2.2.2/lib/origin/extensions/set.rb
/usr/lib64/ruby/gems/2.3.0/gems/origin-2.2.2/lib/origin/extensions/string.rb
/usr/lib64/ruby/gems/2.3.0/gems/origin-2.2.2/lib/origin/extensions/symbol.rb
/usr/lib64/ruby/gems/2.3.0/gems/origin-2.2.2/lib/origin/extensions/time.rb
/usr/lib64/ruby/gems/2.3.0/gems/origin-2.2.2/lib/origin/extensions/time_with_zone.rb
/usr/lib64/ruby/gems/2.3.0/gems/origin-2.2.2/lib/origin/forwardable.rb
/usr/lib64/ruby/gems/2.3.0/gems/origin-2.2.2/lib/origin/key.rb
/usr/lib64/ruby/gems/2.3.0/gems/origin-2.2.2/lib/origin/macroable.rb
/usr/lib64/ruby/gems/2.3.0/gems/origin-2.2.2/lib/origin/mergeable.rb
/usr/lib64/ruby/gems/2.3.0/gems/origin-2.2.2/lib/origin/optional.rb
/usr/lib64/ruby/gems/2.3.0/gems/origin-2.2.2/lib/origin/options.rb
/usr/lib64/ruby/gems/2.3.0/gems/origin-2.2.2/lib/origin/pipeline.rb
/usr/lib64/ruby/gems/2.3.0/gems/origin-2.2.2/lib/origin/queryable.rb
/usr/lib64/ruby/gems/2.3.0/gems/origin-2.2.2/lib/origin/selectable.rb
/usr/lib64/ruby/gems/2.3.0/gems/origin-2.2.2/lib/origin/selector.rb
/usr/lib64/ruby/gems/2.3.0/gems/origin-2.2.2/lib/origin/smash.rb
/usr/lib64/ruby/gems/2.3.0/gems/origin-2.2.2/lib/origin/version.rb
/usr/lib64/ruby/gems/2.3.0/specifications/origin-2.2.2.gemspec
